Product_id=int(input("Enter Product ID: "))
Product_name=input("Enter Product Name: ")
Price=float(input("Enter Price: "))
Categories=list(input("Enter Categories: ").split(","))
Stock_available=int(input("Enter Available Stock: "))
Stock_details=tuple(input("Stock Details: ").split(","))
Discount_Percentage=float(input("Enter Discount Percentage: "))
Product_Features=set(input("Enter Product Features: ").split(","))
Supplier_Details=eval(input("Enter Supplier Name and Contactnumber and Location: ").split())
print("Product_id,Product_name,Price: ",Product_id,Product_name,Price,sep=',')
print("Discount_Percentage: %f" %(Discount_Percentage))
print(f"Product_name:{Product_name} \nPrice:{Price} \nDiscount_Percentage:{Discount_Percentage} \nStock_available:{Stock_available}")
print(f"Supplier_Details:{name} Supplier_Detail:{Contactnumber} Supplier_Detail{Location}")

